Enhancement: Make all lrzip-next files and symlinks unique.
No more overlap with old lrzip.
Update all man pages for new names

diff --git a/src/lrzntar b/src/lrzntar
--- a/src/lrzntar
+++ b/src/lrzntar
@@ -2,6 +2,7 @@
 
 # Copyright (C) George Makrydakis 2009-2011,2013
 # Copyright (C) Con Kolivas 2011-2012,2016,2018,2021
+# Updated 2022 Peter Hyman for lrzip-next
 
 # A bash wrapper for Con Kolivas' excellent lrzip utility. For the time
 # being, lrzip does not like pipes, so we had to do this. It is kind of
@@ -20,31 +21,32 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-function lrztar_local() {
+function lrzntar_local() {
     local hv="\
-lrztar GNU/bash wrapper script for lrzip and tar input/output over directories.
+lrzntar GNU/bash wrapper script for lrzip-next and tar input/output over directories.
 Copyright (C) George Makrydakis 2009-2011,2013
 Copyright (C) Con Kolivas       2011,2012
+Updated 2022 Peter Hyman for lrzip-next compatibility
 
-Usage : lrztar [lrzip options] <directory>
-Result: a lrzip tarball is produced.
-Extras: when an lrzip tarball is used with -d, -O, it gets extracted:
+Usage : lrzntar [lrzip-next options] <directory>
+Result: a lrzip-next tarball is produced.
+Extras: when an lrzip-next tarball is used with -d, -O, it gets extracted:
 
  -h: will display this message.
- -d: <path1> will decompress a <path1> lrzip tarball to current directory.
- -O: <path2> will decompress a -d specified lrzip tarball to <path2> path.
+ -d: <path1> will decompress a <path1> lrzip-next tarball to current directory.
+ -O: <path2> will decompress a -d specified lrzip-next tarball to <path2> path.
  -f: will force overwrites.
 
 Notice:
  - The input argument is always last, all options and their arguments precede.
  - The -O flag is an option flag, goes before: (-O <somedir> <input arg>).
- - You can use the remaining options of lrzip as they were.
- - lrzuntar is equivalent to lrztar [options] -d <filename>.
- - This script exists because of how lrzip behaves.
+ - You can use the remaining options of lrzip-next as they were.
+ - lrznuntar is equivalent to lrzntar [options] -d <filename>.
+ - This script exists because of how lrzip-next behaves.
  - Beware the -f flag, it stands for what it says...
 "
     [[ $1 == "" ]] && {
-        printf "lrztar: no arguments given\n";
+        printf "lrzntar: no arguments given\n";
         return 1;
     }
     local p=("${@:1:$(($#-1))}") s="${!#}" vopt=("lrz") \
@@ -53,20 +55,20 @@ Notice:
           v_T=0 v_N=0 v_v=0 v_f=0 v_d=0 v_h=0 \
           v_H=0 v_c=0 v_k=0 v_o=0 v_O=0 v_m=0 x= i="$(pwd)"
     tar --version &> /dev/null \
-        || { printf "lrztar: no tar in your path\n"; return 1; }
+        || { printf "lrzntar: no tar in your path\n"; return 1; }
     lrzip-next --version &> /dev/null \
-        || { printf "lrztar: no lrzip in your path\n"; return 1; }
-    lrzcat --version &> /dev/null \
-        || { printf "lrztar: no lrzcat in your path\n"; return 1; }
+        || { printf "lrzntar: no lrzip-next in your path\n"; return 1; }
+    lrzncat --version &> /dev/null \
+        || { printf "lrzntar: no lrzncat in your path\n"; return 1; }
     while getopts w:O:S:DqL:nlbgzUm:TN:p:vfo:d:tVhHck x; do
         [[ $x == [tV] ]] && {
-            printf "lrztar: invalid option for lrztar: %s\n" "$x";
+            printf "lrzntar: invalid option for lrzntar: %s\n" "$x";
             return 1;
         }
         ((v_$x=${#vopt[@]}))
         vopt[${#vopt[@]}]="$OPTARG"
     done
-    [[ $(basename "$0") == lrzuntar ]] \
+    [[ $(basename "$0") == lrznuntar ]] \
         && { ((v_d=${#vopt[@]})); vopt[${#vopt[@]}]="$s"; }
     { ! (($#)) || ((v_h)); } && {
         printf "%s\n" "$hv"
@@ -74,7 +76,7 @@ Notice:
     }
     ((v_d)) && {
         [[ -e ${vopt[v_d]} ]] || {
-            printf "lrztar: file does not exist: %s\n" \
+            printf "lrzntar: file does not exist: %s\n" \
                    "${vopt[v_d]}"
             return 1
         }
@@ -91,12 +93,12 @@ Notice:
             i="${vopt[v_O]%/}"
             x="${s##*/}"
             if [[ -d "$i/${x%.tar.*}" ]] && ! ((v_f)); then
-                printf "lrztar: %s exists, use -f.\n" \
+                printf "lrzntar: %s exists, use -f.\n" \
                        "$i/${x%.tar.*}"
                 return 1
             fi
             if ! [[ -d $i ]]; then
-                printf "lrztar: %s output path does not exist.\n" \
+                printf "lrzntar: %s output path does not exist.\n" \
                        "$i"
                 return 1
             fi
@@ -113,14 +115,14 @@ Notice:
     } || {
         if ((v_o)); then
             ! ((v_f)) && [[ -e ${vopt[$v_o]} ]] && {
-                printf "lrztar: %s exists, use -f to overwrite.\n" \
+                printf "lrzntar: %s exists, use -f to overwrite.\n" \
                        "${vopt[$v_o]}"
                 return 1
             }
         else
             if ((v_O)); then
                 if ! [[ -d ${vopt[v_O]} ]]; then
-                    printf "lrztar: %s output path does not exist.\n" \
+                    printf "lrzntar: %s output path does not exist.\n" \
                            "${vopt[v_O]}"
                     return 1
                 fi
@@ -139,7 +141,7 @@ Notice:
         fi
         if ! ((v_o)); then 
             ! ((v_f)) && [[ -e $i/${s##*/}.tar.${vopt[v_S]} ]] && {
-                printf "lrztar: %s exists, use -f to overwrite\n" \
+                printf "lrzntar: %s exists, use -f to overwrite\n" \
                     "$i/${s##*/}.tar.${vopt[v_S]}"
                 return 1
             }
@@ -150,4 +152,4 @@ Notice:
     return $x
 }
 
-lrztar_local "${@}"
+lrzntar_local "${@}"
